# グローバーのアルゴリズム

In [1]:
import numpy as np

In [2]:
number_of_qubits = 8
x_solution = 2

`number_of_qubits`　用意する量子ビットの数 

計算基底は`2**number_of_qubits`個できる


`x_solution` 解の位置（10進数表記)

## オラクルゲートの作成

オラクルゲートは解となる量子状態の確率振幅のみ反転させるため

単位行列を作り(`eye`関数)

次に解がiであれば(i,i)成分を-1にすればよい

In [3]:
#oracle
OracleGate = np.eye(2**(number_of_qubits),dtype='float128')
OracleGate[x_solution,x_solution]=-1
print(OracleGate)

[[ 1.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  0. ...  0.  0.  0.]
 [ 0.  0. -1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]


## 平均値周りの反転ゲートの作成

In [4]:
Inverse_around_Mean = np.ones((2**(number_of_qubits),2**(number_of_qubits)),dtype='float128')
Inverse_around_Mean=Inverse_around_Mean/2**(number_of_qubits-1)
Inverse_around_Mean-=np.eye(2**number_of_qubits,dtype='float128')
print(Inverse_around_Mean)

[[-0.9921875  0.0078125  0.0078125 ...  0.0078125  0.0078125  0.0078125]
 [ 0.0078125 -0.9921875  0.0078125 ...  0.0078125  0.0078125  0.0078125]
 [ 0.0078125  0.0078125 -0.9921875 ...  0.0078125  0.0078125  0.0078125]
 ...
 [ 0.0078125  0.0078125  0.0078125 ... -0.9921875  0.0078125  0.0078125]
 [ 0.0078125  0.0078125  0.0078125 ...  0.0078125 -0.9921875  0.0078125]
 [ 0.0078125  0.0078125  0.0078125 ...  0.0078125  0.0078125 -0.9921875]]


In [5]:
GroverGate = np.dot(Inverse_around_Mean,OracleGate)
print(GroverGate)

[[-0.9921875  0.0078125 -0.0078125 ...  0.0078125  0.0078125  0.0078125]
 [ 0.0078125 -0.9921875 -0.0078125 ...  0.0078125  0.0078125  0.0078125]
 [ 0.0078125  0.0078125  0.9921875 ...  0.0078125  0.0078125  0.0078125]
 ...
 [ 0.0078125  0.0078125 -0.0078125 ... -0.9921875  0.0078125  0.0078125]
 [ 0.0078125  0.0078125 -0.0078125 ...  0.0078125 -0.9921875  0.0078125]
 [ 0.0078125  0.0078125 -0.0078125 ...  0.0078125  0.0078125 -0.9921875]]


## アダマール変換後の量子状態の生成
オラクルゲートと平均値周りの反転ゲートができた。

$H^{\otimes n}|0\rangle$という
アダマール変換で用意した、重ね合わせ状態にグローバーゲート（オラクルゲートと平均値周りの反転ゲート）を繰り返し通す
なお規格化定数は省略した

In [6]:
psi_0 = np.ones(2**number_of_qubits,dtype='float128')
psi_x = np.copy(psi_0)
psi_x_old = np.copy(psi_0)
#psi_0 = np.reshape(psi_0,(8,1))
print(psi_0)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
np.dot(GroverGate,psi_0)

array([0.984375, 0.984375, 2.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984375,
       0.984375, 0.984375, 0.984375, 0.984375, 0.984375, 0.984

In [8]:
psi_x_old = psi_0
j=0
amplitude = []
n_max = 30
for i in range(n_max):
    psi_x = np.dot(GroverGate,psi_x_old)
    print(psi_x)
    amplitude.append(psi_x[x_solution])
    psi_x_old = psi_x

[0.984375 0.984375 2.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375 0.984375
 0.984375 0.984375 0.984375 0.984375 0.984375 0.984

In [9]:
print(amplitude)

[2.984375, 4.922119140625, 6.782955169677734375, 8.53780752420425415, 10.159256636165082455, 11.621967363185831346, 12.903084850156801622, 13.982591636344071873, 14.843620428213466, 15.47271765089202483, 15.860053660275395773, 15.999576331216963515, 15.889105621983266285, 15.530367637406080413, 14.928967658494424551, 14.094302559918793302, 13.039413983844430998, 11.7807845642724993256, 10.3380803858838099165, 8.73384370146568607, 6.993140709212160828, 5.1431698933771955776, 3.2128370479582116382, 1.2323036236648806272, -0.76748454474821413575, -2.7552807671496180534, -4.700025727564309173, -6.5713327859858079263, -8.339962769626278429, -9.978280834991338383]


In [10]:
j=0
for i in range(n_max):
    if amplitude[i+1] < amplitude[i]:
        j=i+1
        break

In [11]:
j

12

最後の出力が解の確率振幅が最初の極大値を迎えるときの繰り返し回数である